name: Run tests with coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  validate_commit:
    name: Validate commit
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6.4.0
        with:
          go-version: '1.26.*'

      - uses: extractions/setup-just@v4

      - name: Check Format
        run: gofmt -d ./

      - name: Verify dependencies
        run: go mod verify

      - name: Install dependencies
        run: go mod vendor

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9

      - name: Setup integration tests
        run: just up

      - name: Run unit tests
        run: go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./... -short

      - name: Get logs from application pods
        if: always()
        run: just logs